menu:
  Blog: /
  About: /about.html
  Archive: /archives

profile_image: https://avatars1.githubusercontent.com/u/860411?s=460&v=4
favico: /assets/favico.png

title: Segfault
subtitle: by alxbl
main_url: https://github.com/alxbl


# Formats
post_date_format: YYYY.MM.DD
archive_date_format: MMM YYYY

social:
  - url: https://github.com/alxbl
    icon: fa-github
    title: alxbl @ github
  - url: https://stackoverflow.com/users/424216/alxbl
    icon: fa-stack-overflow
    title: alxbl @ stackoverflow
  - url: https://twitter.com/alxbl
    icon: fa-twitter
    title: alxbl @ twitter
