menu:

profile_image: https://avatars1.githubusercontent.com/u/860411?s=460&v=4
favico: /assets/favico.png

title: segfault
author: alxbl
main_url: https://github.com/alxbl


# Formats
post_date_format: MMMM DD, YYYY
archive_date_format: MMMM YYYY

social:
  - url: https://github.com/alxbl
    icon: fa-github
    title: alxbl @ github
  - url: https://stackoverflow.com/users/424216/alxbl
    icon: fa-stack-overflow
    title: alxbl @ stackoverflow
  - url: /atom.xml
    icon: fa-rss
    title: ATOM feed
